name: NPM publish

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'release' || github.event.release.target_commitish == 'main'

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.release.target_commitish || github.ref_name }}
          fetch-depth: 0

      # install Node.js
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      # build the project
      - run: npm run build

      # run tests just in case
      - run: npm test

      # publish to NPM with OIDC authentication
      - run: npm publish
